version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - webservice

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - webservice
    depends_on:
      - eureka-server

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - webservice
    depends_on:
      - eureka-server

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - webservice
    depends_on:
      - eureka-server

networks:
  webservice:
    driver: bridge
